on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Docs

jobs:
  Docs:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: "release", pkgdown: "true", latex: "true" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{secrets.GH_PAT}}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Bash Windows over the head with a source install of dplyr
        if: runner.os == 'Windows'
        run: install.packages("dplyr", type = "source")
        shell: Rscript {0}

      - name: Install R dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Setup git and install package
        if: matrix.config.pkgdown == 'true'
        run: |
          git config --global user.name ${{secrets.GH_USER}}
          git config --global user.email ${{secrets.GH_EMAIL}}
          R CMD INSTALL .

      - name: Deploy pkgdown docs
        if: matrix.config.pkgdown == 'true'
        run: |
          remotes::install_dev("pkgdown")
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
