on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "devel" }
          - { os: windows-latest, r: "release" }
          - { os: windows-latest, r: "oldrel" }
          - { os: macOS-latest, r: "devel"}
          - { os: macOS-latest, r: "release"}
          - { os: macOS-latest, r: "oldrel"}
          - { os: ubuntu-latest, r: "devel" }
          - { os: ubuntu-latest, r: "release", pkgdown: "true", latex: "true" }
          - { os: ubuntu-latest, r: "oldrel" }


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      ODKC_URL: ${{secrets.ODKC_URL}}
      ODKC_UN: ${{secrets.ODKC_UN}}
      ODKC_PW: ${{secrets.ODKC_PW}}
      GITHUB_PAT: ${{secrets.GITHUB_PAT}}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Bash Windows over the head with a source install of dplyr
        if: runner.os == 'Windows'
        run: install.packages("dplyr", type = "source")
        shell: Rscript {0}

      - name: Install R dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Report test coverage
        if: matrix.config.pkgdown == 'true'
        run: covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}

      - name: Setup git and install package
        if: matrix.config.pkgdown == 'true'
        run: |
          git config --global user.name ${{secrets.GH_USER}}
          git config --global user.email ${{secrets.GH_EMAIL}}
          R CMD INSTALL .

      - name: Deploy pkgdown docs
        if: matrix.config.pkgdown == 'true'
        run: |
          remotes::install_dev("pkgdown")
          pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
